=== fuchsia-programming/charts/assets/data/schema/sitemap.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="urlset">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="url" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="loc" type="xs:string"></xs:element>
              <xs:element name="lastmod" type="xs:dateTime"></xs:element>
              <xs:element name="priority" type="xs:int"></xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="xmlns" type="xs:string"></xs:attribute>
      <xs:attribute name="xmlns:xsi" type="xs:string"></xs:attribute>
      <xs:attribute name="xsi:schemaLocation" type="xs:string"></xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== fuchsia-programming/charts/sitemap.xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset
  xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
  http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
  <url>
    <loc>http://thebeast.me/charts/</loc>
    <lastmod>2018-03-04T21:48:56+10:00</lastmod>
    <priority>1.00</priority>
  </url>
  <url>
    <loc>http://thebeast.me/charts/index.html</loc>
    <lastmod>2018-03-04T21:48:56+10:00</lastmod>
    <priority>0.80</priority>
  </url>
  <url>
    <loc>http://thebeast.me/charts/index1.html</loc>
    <lastmod>2018-03-04T21:48:56+10:00</lastmod>
    <priority>0.80</priority>
  </url>
  <url>
    <loc>http://thebeast.me/charts/index2.html</loc>
    <lastmod>2018-03-04T21:48:56+10:00</lastmod>
    <priority>0.80</priority>
  </url>
  <url>
    <loc>http://thebeast.me/charts/index3.html</loc>
    <lastmod>2018-03-04T21:48:56+10:00</lastmod>
    <priority>0.80</priority>
  </url>
  <url>
    <loc>http://thebeast.me/charts/index4.html</loc>
    <lastmod>2018-03-04T21:48:56+10:00</lastmod>
    <priority>0.80</priority>
  </url>
  <url>
    <loc>http://thebeast.me/charts/index5.html</loc>
    <lastmod>2018-03-04T21:48:56+10:00</lastmod>
    <priority>0.80</priority>
  </url>
  <url>
    <loc>http://thebeast.me/charts/index6.html</loc>
    <lastmod>2018-03-04T21:48:56+10:00</lastmod>
    <priority>0.80</priority>
  </url>
  <url>
    <loc>http://thebeast.me/charts/index7.html</loc>
    <lastmod>2018-03-04T21:48:56+10:00</lastmod>
    <priority>0.80</priority>
  </url>
  <url>
    <loc>http://thebeast.me/charts/index8.html</loc>
    <lastmod>2018-03-04T21:48:56+10:00</lastmod>
    <priority>0.80</priority>
  </url>
  <url>
    <loc>http://thebeast.me/charts/index9.html</loc>
    <lastmod>2018-03-04T21:48:56+10:00</lastmod>
    <priority>0.80</priority>
  </url>
  <url>
    <loc>http://thebeast.me/charts/index10.html</loc>
    <lastmod>2018-03-04T21:48:56+10:00</lastmod>
    <priority>0.80</priority>
  </url>
  <url>
    <loc>http://thebeast.me/charts/index11.html</loc>
    <lastmod>2018-03-04T21:48:56+10:00</lastmod>
    <priority>0.80</priority>
  </url>
  <url>
    <loc>http://thebeast.me/charts/index12.html</loc>
    <lastmod>2018-03-04T21:48:56+10:00</lastmod>
    <priority>0.80</priority>
  </url>
  <url>
    <loc>http://thebeast.me/charts/index13.html</loc>
    <lastmod>2018-03-04T21:48:56+10:00</lastmod>
    <priority>0.80</priority>
  </url>
  <url>
    <loc>http://thebeast.me/charts/index14.html</loc>
    <lastmod>2018-03-04T21:48:56+10:00</lastmod>
    <priority>0.80</priority>
  </url>
  <url>
    <loc>http://thebeast.me/charts/index15.html</loc>
    <lastmod>2018-03-04T21:48:56+10:00</lastmod>
    <priority>0.80</priority>
  </url>
</urlset>
